name: Test

on:
  push:
    branches: [main, "feature/*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: "16"
          distribution: "adopt"
      - name: Run tests
        run: sbt test
    services:
      surrealdb:
        image: surrealdb/surrealdb:1.0.0-beta.8
        env:
          USER: root
          PASS: root
          LOG: debug
        ports: 
          - 8000:8000